### ISSUE TITLE
Error when trying to install NSNSDAcoustics

### ISSUE THREAD

**Issue by vladkov88** [nationalparkservice/NSNSDAcoustics#1]
Hello,

I get the following error when I attempt to install the package:
```
Error in .install_package_code_files(".", instdir) : 
files in 'Collate' field missing from 'C:/Users/vladk/AppData/Local/Temp/RtmpagvOJn/R.INSTALL2e98702075ac/NSNSDAcoustics/R':
  bcp-functions.R
  nvspl_to_ai.R
ERROR: unable to collate and parse R files for package 'NSNSDAcoustics'
* removing 'C:/Users/vladk/Documents/R/win-library/4.1/NSNSDAcoustics'
```

Thanks in advance!

-Vlad

**Comment by cbalantic** [comment]
Hi Vlad,

Thank you for attempting an install! We don't have a stable release of the package yet, but perhaps the function code can provide inspiration or utility in the meantime. I just found out that BirdNET underwent a major update in April 2022. And coincidentally, PAMGuide (upon which the wave_to_nvspl function is based) also just went through a minor update. I will need to do a big overhaul on all of this before it will be useful to anyone else. Let me know if I can help with anything in the meantime though.

If you were interested in the BirdNET functions, it looks like they've added in a GUI and some other cool features that might be helpful: https://github.com/kahst/BirdNET-Analyzer

**Comment by cbalantic** [comment]
Hi Vlad, just an update that this issue is now fixed and install_github() should work. During the install process, you may be prompted to update other packages and/or Rtools, and can follow any prompts accordingly. 

I still don't consider the package in a stable state overall, but the BirdNET functions are stable for now, in case you are interested in them. Please feel free to open additional issues if you end up trying any of these.

**Comment by vladkov88** [comment]
Thanks so much, Cathleen!

Best,
Vlad Kovalenko
(he, him, his)
________________________________

**Comment by vladkov88** [comment]
Hi Cathleen,

Sorry to bug you again, but I just tried to install the package again and got the following error:

Error: Failed to install 'NSNSDAcoustics' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr:
E> * checking for file 'C:\Users\vladk\AppData\Local\Temp\RtmpqkZTBf\remotes37f07e64121b\nationalparkservice-NSNSDAcoustics-0a119f0/DESCRIPTION' ... OK
E> * preparing 'NSNSDAcoustics':
E> * checking DESCRIPTION meta-information ... ERROR
E> ***@***.*** field gives no person with maintainer role, valid email
E> address and non-empty name.
E>
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.

Thanks for your help!

Best,
Vlad Kovalenko
(he, him, his)
________________________________

**Comment by cbalantic** [comment]
Vlad, no worries, it's super helpful to have someone attempting an install since I'm working on this alone at the moment! I've fixed the DESCRIPTION file which was causing this problem.  Commit [2b5e73c](https://github.com/nationalparkservice/NSNSDAcoustics/commit/2b5e73c2ee4f7c74a264f1192467ab5cf9a46449). I'm able to get it to install on a different machine. Does it work for you now?

**Comment by vladkov88** [comment]
Thanks for the quick response, Cathleen!

Now I get this:

Warning: package 'monitoR' was built under R version 4.1.3
Warning: package 'tuneR' was built under R version 4.1.3
Error: package or namespace load failed for 'tuneR' in library.dynam(lib, package, package.lib):
 DLL 'signal' not found: maybe not installed for this architecture?
Error : package 'tuneR' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
Warning: package 'monitoR' was built under R version 4.1.3
Warning: package 'tuneR' was built under R version 4.1.3
Warning: replacing previous import 'monitoR::readMP3' by 'tuneR::readMP3' when loading 'NSNSDAcoustics'
Warning: replacing previous import 'data.table::week' by 'lubridate::week' when loading 'NSNSDAcoustics'
ERROR: loading failed for 'i386'
* removing 'C:/Users/vladk/Documents/R/win-library/4.1/NSNSDAcoustics'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/vladk/AppData/Local/Temp/RtmpqkZTBf/file37f01d394f24/NSNSDAcoustics_0.0.0.9000.tar.gz’ had non-zero exit status

Best,
Vlad Kovalenko
(he, him, his)
________________________________

**Comment by cbalantic** [comment]
Hi Vlad, what a journey! This install works on a Windows machine running R 4.1.2, and on another Windows machine running R 4.2.0. Do you still get this error if you update R to the latest version (4.2.0?).

Feel free to contact me at cathleen_balantic@nps.gov and maybe we could set up a virtual meeting to troubleshoot.

**Comment by vladkov88** [comment]
That worked! Thanks Cathleen 🙂

Best,
Vlad
________________________________
