### ISSUE TITLE
birdnet_format issue resulting in altered recordingID and downstream errors in birdnet_barchart

### ISSUE THREAD

**Issue by Kayley-Dillon** [nationalparkservice/NSNSDAcoustics#6]
This issue only seems to occur if a BirdNET text file doesn't include any species detections. When birdnet_format is run, it adds "BirdNET_" to the beginning of the recordingID. 

When these formatted files are set up using the documented process and input into birdnet_barchart, the locationID is misread as "BirdNET" and the date and time fields are filled with "NA" values. I think the function is missing the date and time information because the recordingID field is no longer in the expected format. birdnet_barchart then produces an error stating that julian.range must be a finite number, which I believe is due to NAs appearing in the date and time fields.

**Comment by cbalantic** [comment]
In birdnet_format(), removed faulty appending of BirdNET_ to recordingID that occurs when there are no detections in a recording. In birdnet_barchart(), eliminated "NA" recordings from the summary barchart to prevent an NA species from being plotted. Changes are here: https://github.com/nationalparkservice/NSNSDAcoustics/commit/8b41ffb5e5d55d8371823c14e4a7d2c50ec220d1
